name: Build Flatpak Repository

on: workflow_dispatch

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:45
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install org.freedesktop.Platform
        run: flatpak install --noninteractive flathub org.freedesktop.Platform//23.08

      - name: Install org.freedesktop.Sdk
        run: flatpak install --noninteractive flathub org.freedesktop.Sdk//23.08
 
      - name: Build
        id: build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/io.github.joyrider3774.formula_1_game__watch_playdate.yml
            build-aux/io.github.joyrider3774.retrotime.yml
            build-aux/io.github.joyrider3774.blockdude_playdate.yml
            build-aux/io.github.joyrider3774.puztrix_playdate.yml
            build-aux/io.github.joyrider3774.checkers_playdate.yml
            build-aux/io.github.joyrider3774.rubido_playdate.yml
            build-aux/io.github.joyrider3774.dynamate_playdate.yml
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true
          upload-bundles: true
          upload-pages-includes: |
            index.html
            joyrider3774.flatpakrepo
            icon.svg
            
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Flatpak
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
